# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
