# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
