# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[(b'art/design', b'art/design'), (b'fashion', b'fashion'), (b'entertainment', b'entertainment'), (b'sports', b'sports'), (b'campustour', b'campustour'), (b'well-being', b'well-being'), (b'nature', b'nature'), (b'food', b'food'), (b'life style', b'life style'), (b'history', b'history'), (b'music', b'music'), (b'business', b'business'), (b'bar/club', b'bar/club')], default=b'art/design', max_length=20)),
                ('activityLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('activityIntroduction', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=30, null=True)),
                ('meetingPlace', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('maximumCapacity', models.IntegerField(default=0)),
                ('additionalInformation', models.CharField(blank=True, max_length=500, null=True)),
                ('readyTime', models.FloatField(default=0.0)),
                ('lastReadyTime', models.FloatField(default=0.0)),
                ('activityRating', models.FloatField(default=0.0)),
                ('totalTime', models.FloatField(default=0.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'Kor', b'Korean'), (b'Eng', b'English'), (b'Jap', b'Japanese'), (b'Chin', b'Chinese')], default=b'Korean', max_length=30)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('rating', models.FloatField(default=0.0)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('startYear', models.IntegerField(default=0)),
                ('startMonth', models.IntegerField(default=0)),
                ('startHour', models.IntegerField(default=0)),
                ('startMinute', models.IntegerField(default=0)),
                ('endYear', models.IntegerField(default=0)),
                ('endMonth', models.IntegerField(default=0)),
                ('endDay', models.IntegerField(default=0)),
                ('endHour', models.IntegerField(default=0)),
                ('endMinute', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=500, null=True)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=20)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
