# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('art/design', 'art/design'), ('fashion', 'fashion'), ('entertainment', 'entertainment'), ('sports', 'sports'), ('campustour', 'campustour'), ('well-being', 'well-being'), ('nature', 'nature'), ('food', 'food'), ('life style', 'life style'), ('history', 'history'), ('music', 'music'), ('business', 'business'), ('bar/club', 'bar/club')], default='art/design', max_length=20)),
                ('language', models.CharField(choices=[('Kor', 'Korean'), ('Eng', 'English'), ('Jap', 'Japanese'), ('Chin', 'Chinese')], default='Korean', max_length=30)),
                ('activityLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('activityIntroduction', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=30, null=True)),
                ('meetingPlace', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('maximumCapacity', models.IntegerField(default=0)),
                ('additionalInformation', models.CharField(blank=True, max_length=500, null=True)),
                ('readyTime', models.FloatField(default=0.0)),
                ('lastReadyTime', models.FloatField(default=0.0)),
                ('activityRating', models.FloatField(default=0.0)),
                ('totalTime', models.FloatField(default=0.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('rating', models.FloatField(default=0.0)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('startYear', models.IntegerField(default=0)),
                ('startMonth', models.IntegerField(default=0)),
                ('startHour', models.IntegerField(default=0)),
                ('startMinute', models.IntegerField(default=0)),
                ('endYear', models.IntegerField(default=0)),
                ('endMonth', models.IntegerField(default=0)),
                ('endDay', models.IntegerField(default=0)),
                ('endHour', models.IntegerField(default=0)),
                ('endMinute', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=500, null=True)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=20)),
                ('activityIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
