# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activityLocation',
            new_name='gatheringityLocation',
        ),
    ]
