# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tp',
            new_name='type',
        ),
    ]
