# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinfo',
            name='activityRating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='lastReadyTime',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='maximumCapacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='readyTime',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='totalTime',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
