# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20170820_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='gatheringityLocation',
            new_name='gatheringLocation',
        ),
    ]
