# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20170816_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinfo',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
