# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_auto_20170824_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('art/design', 'art/design'), ('fashion', 'fashion'), ('entertainment', 'entertainment'), ('sports', 'sports'), ('campustour', 'campustour'), ('well-being', 'well-being'), ('nature', 'nature'), ('food', 'food'), ('life style', 'life style'), ('history', 'history'), ('music', 'music'), ('business', 'business'), ('bar/club', 'bar/club')], default='art/design', max_length=30)),
                ('language', models.CharField(choices=[('Korean', 'Korean'), ('English', 'English'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese')], default='Korean', max_length=30)),
                ('activityLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('activityIntroduction', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=30, null=True)),
                ('gatheringLocation', models.CharField(blank=True, max_length=128, null=True)),
                ('meetingPlace', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('maximumCapacity', models.IntegerField(blank=True, default=0, null=True)),
                ('additionalInformation', models.CharField(blank=True, max_length=500, null=True)),
                ('readyTime', models.FloatField(blank=True, default=0.0, null=True)),
                ('lastReadyTime', models.FloatField(blank=True, default=0.0, null=True)),
                ('activityRating', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalTime', models.FloatField(blank=True, default=0.0, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='activitylanguage',
            name='activityIndex',
        ),
        migrations.AlterField(
            model_name='activitypicture',
            name='activityIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo'),
        ),
        migrations.AlterField(
            model_name='activityreview',
            name='activityIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo'),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='activityIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo'),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='endDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='endHour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='endMinute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='endMonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='endYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='startHour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='startMinute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='startMonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='startYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='activityIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='activityIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityInfo'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityLanguage',
        ),
    ]
