# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=5)),
                ('tp', models.CharField(default='G', max_length=5)),
                ('birth', models.CharField(max_length=10)),
            ],
        ),
    ]
