# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20170720_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
