# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=25)),
                ('gender', models.CharField(default='', max_length=5)),
                ('type', models.CharField(default='G', max_length=5)),
                ('birth', models.DateField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
