# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Register',
        ),
    ]
