# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_remove_register_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='id',
        ),
    ]
