# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20170721_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
