# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20170721_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
