# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.URLField()),
                ('university', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=175)),
                ('introduction', models.CharField(max_length=500)),
                ('universityIntroduction', models.CharField(max_length=500)),
                ('totalRating', models.FloatField()),
            ],
        ),
    ]
