# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='id',
            new_name='user_id',
        ),
    ]
