# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20170822_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='location',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='totalRating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='host',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='universityIntroduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
